import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import nodemailer from "npm:nodemailer@6.9.7" 

const GMAIL_USER = Deno.env.get('GMAIL_USER')
const GMAIL_PASS = Deno.env.get('GMAIL_PASS')

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: { user: GMAIL_USER, pass: GMAIL_PASS },
})

serve(async (req) => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  }

  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { to, subject, description, type, status, id, lat, lng } = await req.json()
    let htmlContent = ''
    let emailSubject = subject || "FireWatch Notification"

    // 🟢 TEMPLATE 1: TACTICAL REPLY (Clean, Professional, "Memo" Style)
    if (type === 'reply') {
        const accent = '#3b82f6' // Tactical Blue
        htmlContent = `
          <div style="font-family: 'Courier New', monospace; max-width: 600px; margin: 0 auto; background-color: #f8fafc; border: 1px solid #e2e8f0; border-left: 6px solid ${accent};">
            
            <div style="padding: 20px; border-bottom: 1px solid #e2e8f0; background-color: #fff;">
               <h2 style="color: ${accent}; margin: 0; font-size: 18px; letter-spacing: 2px; text-transform: uppercase;">FireWatch Command</h2>
               <p style="font-size: 10px; color: #64748b; margin: 5px 0 0 0;">REF: ${id} // SECURE_UPLINK</p>
            </div>

            <div style="padding: 30px; background-color: #ffffff; color: #334155; line-height: 1.6; font-size: 14px;">
               <p style="margin-top: 0; white-space: pre-wrap;">${description}</p>
            </div>

            <div style="padding: 15px 20px; background-color: #f1f5f9; color: #94a3b8; font-size: 10px; border-top: 1px solid #e2e8f0;">
               <p style="margin: 0;"><strong>TRANSMISSION LOG:</strong></p>
               <p style="margin: 5px 0 0 0;">This message was generated by the FireWatch Admin Console. Replies to this thread are monitored.</p>
            </div>
          </div>
        `
    } 
    // 🟢 TEMPLATE 2: REPORT CONFIRMATION (For Hazard Reporting)
    else if (type === 'confirmation') {
        emailSubject = `🔥 FireWatch: Report Received`
        htmlContent = `
          <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
            <h2 style="color: #f97316;">FireWatch Report Logged</h2>
            <p><strong>Reference ID:</strong> #${id || 'PENDING'}</p>
            <p>Your report has been received and is being processed by the nearest response node.</p>
            <hr style="border:0; border-top:1px solid #eee; margin: 15px 0;">
            <p><strong>Payload:</strong> ${description}</p>
            ${lat ? `<p><a href="http://maps.google.com/maps?q=${lat},${lng}">View Coordinates</a></p>` : ''}
          </div>
        `
    } 
    // 🟢 TEMPLATE 3: ALERTS (For Critical Updates)
    else {
        const isDanger = status === 'verified'
        const color = isDanger ? '#dc2626' : '#16a34a'
        htmlContent = `
          <div style="font-family: Arial, sans-serif; padding: 20px; border: 4px solid ${color}; border-radius: 8px;">
            <h1 style="color: ${color}; margin-top:0;">${isDanger ? '⚠️ DANGER ALERT' : '✅ STATUS CLEAR'}</h1>
            <p style="font-size: 16px;">${description}</p>
             ${isDanger ? `<p style="color:red; font-weight:bold;">DRONES DISPATCHED TO COORDINATES.</p>` : ''}
          </div>
        `
    }

    // --- SEND EMAIL ---
    console.log(`📨 Sending via Gmail to: ${to}`)
    
    const info = await transporter.sendMail({
      from: `"FireWatch Command" <${GMAIL_USER}>`, 
      to: to, 
      subject: emailSubject,
      html: htmlContent,
    })

    console.log("✅ Email sent successfully:", info.messageId)

    return new Response(JSON.stringify({ success: true, id: info.messageId }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error("❌ Gmail Error:", error)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})